
import = ["~/.config/alacritty/themes/github_dark_dimmed.toml"]

# Font configuration
[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
size = 14.0
